# Generated by Django 3.2.25 on 2025-08-12 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='题目标题')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('options', models.JSONField(verbose_name='选项')),
                ('answer', models.JSONField(verbose_name='正确答案')),
                ('type', models.CharField(choices=[('single', '单选'), ('multiple', '多选'), ('judge', '判断')], max_length=10, verbose_name='题目类型')),
                ('score', models.IntegerField(default=1, verbose_name='分值')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='解析')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '选择题',
                'verbose_name_plural': '选择题',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChoiceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.JSONField(verbose_name='选择的答案')),
                ('is_correct', models.BooleanField(verbose_name='是否正确')),
                ('score', models.IntegerField(verbose_name='得分')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choice.choiceproblem', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '选择题提交记录',
                'verbose_name_plural': '选择题提交记录',
                'ordering': ['-submitted_at'],
                'unique_together': {('problem', 'user')},
            },
        ),
    ]
