# Generated by Django 3.2.25 on 2025-08-12 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0016_auto_20250812_0749'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('choice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='选项内容')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确答案')),
                ('sequence', models.IntegerField(verbose_name='显示顺序')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='problem.problem')),
            ],
            options={
                'verbose_name': '选择题选项',
                'verbose_name_plural': '选择题选项',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ChoiceSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_submits', to='problem.problem')),
                ('selected_options', models.ManyToManyField(related_name='submits', to='choice.ChoiceOption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_submits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '选择题提交',
                'verbose_name_plural': '选择题提交',
            },
        ),
        migrations.AlterUniqueTogether(
            name='choicesubmission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='choicesubmission',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='choicesubmission',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChoiceProblem',
        ),
        migrations.DeleteModel(
            name='ChoiceSubmission',
        ),
    ]
