# Generated by Django 3.2.25 on 2025-08-12 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0011_auto_20250812_2044'),
        ('choice', '0002_auto_20250812_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.TextField(db_index=True)),
                ('is_public', models.BooleanField(default=False)),
                ('title', models.TextField(verbose_name='题目标题')),
                ('description', utils.models.RichTextField(verbose_name='题干')),
                ('explanation', utils.models.RichTextField(blank=True, null=True, verbose_name='解析')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(null=True)),
                ('visible', models.BooleanField(default=True)),
                ('difficulty', models.TextField(verbose_name='难度')),
                ('is_multiple', models.BooleanField(default=False, verbose_name='是否多选题')),
                ('submission_number', models.BigIntegerField(default=0)),
                ('correct_number', models.BigIntegerField(default=0)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.contest')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '选择题',
                'verbose_name_plural': '选择题',
                'db_table': 'choice_problem',
                'ordering': ('create_time',),
                'unique_together': {('_id', 'contest')},
            },
        ),
        migrations.CreateModel(
            name='ChoiceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='choice.choiceproblem')),
            ],
            options={
                'verbose_name': '选择题提交',
                'verbose_name_plural': '选择题提交',
            },
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='content',
            field=utils.models.RichTextField(verbose_name='选项内容'),
        ),
        migrations.DeleteModel(
            name='ChoiceSubmit',
        ),
        migrations.AddField(
            model_name='choicesubmission',
            name='selected_options',
            field=models.ManyToManyField(related_name='submissions', to='choice.ChoiceOption'),
        ),
        migrations.AddField(
            model_name='choicesubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='choice.choiceproblem'),
        ),
    ]
