# Generated by Django 3.2.25 on 2025-08-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0015_auto_20250812_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='problem_type',
        ),
    ]
