# Generated by Django 3.2.25 on 2025-08-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0016_auto_20250812_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_type',
            field=models.TextField(default='Programming'),
        ),
    ]
